# Generated by Django 5.2 on 2025-04-28 14:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('npwp', models.CharField(max_length=255)),
                ('year_of_joining', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=255)),
                ('skt', models.CharField(max_length=255)),
            ],
        ),
    ]
