# Generated by Django 5.2 on 2025-05-01 10:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iconist_app', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplikasi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_aplikasi', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('tahun_dijalankan', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_vendor', models.CharField(max_length=50, unique=True)),
                ('npwp_company', models.CharField(max_length=50)),
                ('nama_company', models.CharField(max_length=100)),
                ('skt_company', models.CharField(max_length=100)),
                ('tahun_kerjasama', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Direktorat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_direktorat', models.CharField(max_length=255)),
                ('skt_direktorat', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_jabatan', models.CharField(max_length=255)),
                ('skt_jabatan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Seksi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_sie', models.CharField(max_length=255)),
                ('skt_sie', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Divisi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_divisi', models.CharField(max_length=255)),
                ('skt_divisi', models.TextField(blank=True, null=True)),
                ('id_direktorat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisis', to='iconist_app.direktorat')),
            ],
        ),
        migrations.CreateModel(
            name='Bidang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_bidang', models.CharField(max_length=255)),
                ('skt_bidang', models.TextField(blank=True, null=True)),
                ('id_divisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidangs', to='iconist_app.divisi')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tgl_bergabung', models.DateField()),
                ('tgl_kontrak_berakhir', models.DateField()),
                ('status_personil_company', models.CharField(max_length=50)),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.company')),
                ('id_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryJabatan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tanggal_awal_jabatan', models.DateField()),
                ('tanggal_akhir_jabatan', models.DateField(blank=True, null=True)),
                ('id_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.employee')),
                ('id_jabatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.jabatan')),
            ],
        ),
        migrations.CreateModel(
            name='PersonilAplikasi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tanggal_pemegangan', models.DateField()),
                ('status_personil_aplikasi', models.CharField(max_length=100)),
                ('id_aplikasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.aplikasi')),
                ('id_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='HistorySie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tanggal_join', models.DateField()),
                ('status_personil_sie', models.CharField(max_length=50)),
                ('id_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.employee')),
                ('id_seksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.seksi')),
            ],
        ),
        migrations.AddField(
            model_name='aplikasi',
            name='id_seksi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.seksi'),
        ),
        migrations.CreateModel(
            name='SubBidang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_sbi', models.CharField(max_length=255)),
                ('skt_sbi', models.TextField(blank=True, null=True)),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.bidang')),
            ],
        ),
        migrations.AddField(
            model_name='seksi',
            name='id_sub_bidang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.subbidang'),
        ),
    ]
