# Generated by Django 5.2 on 2025-05-01 11:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iconist_app', '0003_aplikasi_company_direktorat_jabatan_seksi_divisi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrasiIconapps',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('nilai_kerapian', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kehadiran', models.IntegerField()),
                ('jks', models.IntegerField()),
                ('jkp', models.IntegerField()),
                ('id_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('id_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='StatusKaryawan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('tanggal_modified', models.DateTimeField(auto_now=True)),
                ('nip_modified', models.CharField(max_length=50)),
                ('id_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.employee')),
            ],
        ),
    ]
