# Generated by Django 5.2 on 2025-05-01 11:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iconist_app', '0004_integrasiiconapps_login_statuskaryawan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankSoalSurveyRekan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nip', models.CharField(max_length=50)),
                ('tanggal_pembuatan', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BobotKriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keterangan', models.CharField(max_length=255)),
                ('bobot', models.FloatField()),
                ('atribut', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KomponenPenilaian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deskripsi_komponen', models.TextField()),
                ('tanggal_buat', models.DateTimeField(auto_now_add=True)),
                ('bobot_komponen', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BankSoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_bank_soal', models.CharField(max_length=255)),
                ('tanggal_pembuatan', models.DateField()),
                ('id_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AssignPenilaian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awal_periode', models.DateField()),
                ('akhir_periode', models.DateField()),
                ('awal_penilaian', models.DateField()),
                ('akhir_penilaian', models.DateField()),
                ('id_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.employee')),
                ('id_sub_bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.subbidang')),
                ('id_bank_soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.banksoal')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrasiITSM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jumlah_tiket_sla2', models.PositiveIntegerField(default=0)),
                ('jumlah_tiket_sla3', models.PositiveIntegerField(default=0)),
                ('jumlah_tiket_breach', models.PositiveIntegerField(default=0)),
                ('jumlah_tiket_non_sla', models.PositiveIntegerField(default=0)),
                ('rata_rata_waktu_resolved', models.FloatField()),
                ('rata_rata_peformance', models.FloatField()),
                ('tanggal', models.DateField()),
                ('id_aplikasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrasi_itsm', to='iconist_app.aplikasi')),
                ('id_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Kompetensi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_kompetensi', models.CharField(max_length=100)),
                ('bobot', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tanggal_buat', models.DateField()),
                ('id_bank_soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.banksoal')),
            ],
        ),
        migrations.CreateModel(
            name='MTTR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_sla', models.DecimalField(decimal_places=2, max_digits=8)),
                ('score_xsla', models.DecimalField(decimal_places=2, max_digits=8)),
                ('avg_time', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bonus_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('normal_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('individual_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Pembobotan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('id_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.employee')),
                ('id_kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.bobotkriteria')),
            ],
        ),
        migrations.CreateModel(
            name='PerankinganKaryawan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rank', models.IntegerField()),
                ('id_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.employee')),
                ('id_pembobotan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.pembobotan')),
            ],
        ),
        migrations.CreateModel(
            name='SetPenilaianJabatan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_jabatan', models.CharField(max_length=100)),
                ('ket_otomatisasi_nilai', models.TextField(blank=True, null=True)),
                ('id_assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.assignpenilaian')),
                ('id_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.employee')),
                ('id_komponen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.komponenpenilaian')),
            ],
        ),
        migrations.CreateModel(
            name='PenilaianSpv',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_bank_soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.banksoal')),
                ('id_dinilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_spv_dinilai', to='iconist_app.employee')),
                ('id_menilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_spv_menilai', to='iconist_app.employee')),
                ('id_set_penilaian_jabatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.setpenilaianjabatan')),
            ],
        ),
        migrations.CreateModel(
            name='HasilPenilaian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('id_dinilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_penilaian_dinilai', to='iconist_app.employee')),
                ('id_menilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_penilaian_menilai', to='iconist_app.employee')),
                ('id_set_penilaian_jabatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.setpenilaianjabatan')),
            ],
        ),
        migrations.CreateModel(
            name='SoalSurveyRekan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bobot', models.DecimalField(decimal_places=2, max_digits=5)),
                ('soal', models.TextField()),
                ('tanggal', models.DateField()),
                ('id_bank_soal_survey_rekan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.banksoalsurveyrekan')),
            ],
        ),
        migrations.CreateModel(
            name='PenilaianRekan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_dinilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_rekan_dinilai', to='iconist_app.employee')),
                ('id_menilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_rekan_menilai', to='iconist_app.employee')),
                ('id_set_penilaian_jabatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.setpenilaianjabatan')),
                ('id_soal_survey_rekan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.soalsurveyrekan')),
            ],
        ),
        migrations.CreateModel(
            name='SubKompetensi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_sub', models.CharField(max_length=100)),
                ('bobot_sub', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_kompetensi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.kompetensi')),
            ],
        ),
        migrations.AddField(
            model_name='komponenpenilaian',
            name='id_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iconist_app.subkompetensi'),
        ),
    ]
